from django.conf import settings
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from main.Alice_Blue_Api import SymbolExpirDateListView
from main.angleapi import SymbolExpiryDateListView
from main.companyprofile import *
from main.permissions import RolePermissionListView, UpdateRolePermissionsView
from main.upstock import *
from main.fivepaisa import *
from .views import *
from django.conf.urls.static import static
from main import views
from main.dematemodule import BrokerCallbackView, CheckTokenValidityView, GetClientBrokerDetailsSettingView, LoginDematAPIView,BrokerLoginRedirectView
urlpatterns = [
    path('signup/', UserRegistrationView.as_view(), name='user-registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user-activity-log/', UserActivityLogView.as_view(), name='user-activity-log'),
    # path('user-login-logout/', UserLastLoginLogoutAPIView.as_view(), name='user-login-logout'),
    path('verify-otp/', OTPVerifyView.as_view(), name='otp_verify'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend_otp'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('password-reset-request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset-confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('create-roles/', RoleListCreateView.as_view(), name='role-list-create'),
    path('get-role-subadmin/', GetRoleListAPIView.as_view(), name='get-sub-admin-role-list'),
    path('get-roles-list/', GetRoleListAPIView.as_view(), name='role-list'),
    path('delete-roles/<int:id>/', RoleDeleteView.as_view(), name='role-delete'),
    path('roles/<int:pk>/', RoleDetailView.as_view(), name='role-detail'),
    path('user/<int:pk>/', GetUser.as_view(), name='GetUser'),
    path('users/<int:pk>/assign-role/', UserAssignRoleView.as_view(), name='assign-role'),
    path('get-subadmins-list/', SubadminsView.as_view(), name='sub-admins '),
    path('users-list/', UserManagementView.as_view(), name='user-management'),
    path('create-user/', UserManagementView.as_view(), name='user-management'),
    path('update-user/<int:pk>/', UserManagementView.as_view(), name='user-management'),
    path('delete-user/<int:pk>/', UserManagementView.as_view(), name='user-detail-management'),
    path('user-profile/', UserProfileView.as_view(), name='user-profile'),
    path('kyc/', GetKYCView.as_view(), name='get-kyc'),
    path('get-kyc-by-id/<int:pk>/', GetKYCByIdView.as_view(), name='get-kyc-by-id'),
    path('kyc/update/', CreateOrUpdateKYCView.as_view(), name='create-update-kyc'),
    path('pending-kyc-list/', PendingKYCListView.as_view(), name='kyc-pending-list'),
    path('kyc/verify/<int:kyc_id>/', KYCVerificationView.as_view(), name='kyc-verification'),
    path('update-role-permissions/<int:role_id>/', UpdateRolePermissionsView.as_view(), name='update-role-permissions'),
    path('role-permissions/', RolePermissionListView.as_view(), name='role-permissions-list'),
    path('v2/algo/webhook/', PlaceOrderWebhookView.as_view(), name='webhook2'),
    path('v1/algo/webhook/', MyPlaceOrderWebhookView.as_view(), name='webhook'),
    path('get-alice-orders/', GetAliceOrderBook.as_view(), name='get-order-book'),
    path('get-alice-tread-history/', GetAliceTreadBook.as_view(), name='get-tread-book'),
    path('order-logs-list/', OrderLogListView.as_view(), name='order-log-list'),
    path('user-activity-logs/', UserActivityLogListView.as_view(), name='user-activity-logs'),
    path('user-last-login/', LastLoginActivityView.as_view(), name='last-login'),
    path('get-city-data/',Get_city_data.as_view(), name='cites'),
    path('cities/search/', CitySearchView.as_view(), name='city-search'),
    path('get-state-data/',GetStatesView.as_view(), name='cites'),
    path('state/search/', SearchStatesView.as_view(), name='state-search'),
    path('get-segments/', SegmentAPIView.as_view(), name='segment-list-create'),  
    path('get-segments-list/', SegmentlistAPIView.as_view(), name='segment-list'), 
    path('create-segments/', SegmentAPIView.as_view(), name='post-segment-detail'), 
    path('update-segments/<int:pk>/', SegmentAPIView.as_view(), name='edit-segment-detail'),  
    path('delete-segments/<int:pk>/', SegmentAPIView.as_view(), name='delete-segment-detail'), 
    path('create-category/', CategoryAPIView.as_view(), name='category-create'), 
    path('get-category/', CategoryAPIView.as_view(), name='category-detail'), 
    path('get-category-list/', CategorylistAPIView.as_view(), name='category-detail-list'), 
    path('update-category/<int:pk>/', CategoryAPIView.as_view(), name='update-category-detail'), 
    path('delete-category/<int:pk>/', CategoryAPIView.as_view(), name='delete-category-detail'), 
    path('create-License/', LicenseAPIView.as_view(), name='License-create'), 
    path('get-License/', LicenseAPIView.as_view(), name='License-detail'), 
    path('update-License/<int:pk>/', LicenseAPIView.as_view(), name='update-License-detail'), 
    path('delete-License/<int:pk>/', LicenseAPIView.as_view(), name='delete-License-detail'),
    path('get-services/', ServiceAPIView.as_view(), name='service-list'),
    path('get-services-list/', ServicelistAPIView.as_view(), name='service-list-data'),
    path('create-services/', ServiceAPIView.as_view(), name='create-service'),
    path('update-services/<int:pk>/', ServiceAPIView.as_view(), name='update-service-detail'),
    path('delete-services/<int:pk>/', ServiceAPIView.as_view(), name='delete-service-detail'),
    path('get-group-service/',GroupServiceView.as_view(),name='group-view'),
    path('get-group-service-list/',GroupServicelistView.as_view(),name='group-view-list'),
    path('create-group-service/',GroupServiceView.as_view(),name='group-create'),
    path('update-group-service/<int:pk>/',GroupServiceView.as_view(),name='update-group-view'),
    path('delete-group-service/<int:pk>/',GroupServiceView.as_view(),name='delete-group-view'),
    path('delete-groupservice-json/<int:pk>/', GroupServiceView.as_view(), name='update-group-json-detail'),
    path('edit-groupservice-json/<int:pk>/', GroupServiceJsonUpdateView.as_view(), name='update-group-service-detail'),
    path('add-strategies/', StrategyAPIView.as_view(), name='add-strategy-list'),
    path('get-strategies/', StrategyAPIView.as_view(), name='get-strategy-list'),
    path('update-strategies/<int:pk>/', StrategyAPIView.as_view(), name='update-strategy-detail'),
    path('delete-strategies/<int:pk>/', StrategyAPIView.as_view(), name='delete-strategy-detail'),
    path('add-broker/', BrokerView.as_view(), name='add-broker-list'),
    path('get-broker/', BrokerView.as_view(), name='get-broker-list'),
    path('update-broker/<int:pk>/', BrokerView.as_view(), name='update-broker-detail'),
    path('delete-broker/<int:pk>/', BrokerView.as_view(), name='delete-broker-detail'),
    path('get-strategies-by-id/<int:pk>/', GetStrategyAPIView.as_view(), name='strategies'),
    path('get-strategies-client/<int:pk>/', GetStrategyAPIView.as_view(), name='get-strategy-client'),
    path('get-Groupservices-by-id/<int:pk>/', GetGroupServiceAPIView.as_view(), name='groupservice'),
    path('get-services-Qty_details/<int:id>/', Group_ServicesQtyAPIView.as_view(), name='Services-Qty'),
    path('create-client/', ClientCreateView.as_view(), name='create-client'),
    path('get-client-list/', ClientCreateView.as_view(), name='get-client'),
    path('get-strategy-clients-list/', ClientCreateView.as_view(), name='get-client'),
    path('update-client/<int:pk>/', ClientCreateView.as_view(), name='update-client'),
    path('delete-client/<int:pk>/', ClientCreateView.as_view(), name='delete-client'),
    path('assign-client-to-strategy/<int:pk>/', AssignClientToStrategyAPIView.as_view(), name='assign-client-to-strategy'),
    path('get-client-by-id/<int:pk>/', GetclientbyidPIView.as_view(), name='subuser-list'),
    path('enable-client/<int:pk>/', ClientCreateView.as_view(), name='update-client'),
    path('get-client-services/<int:pk>/', ClientTreadSettingView.as_view(), name='get-client-services'),
    path('update-client-trading-setting/<int:pk>/', ClientTreadSettingView.as_view(), name='update-client-trading'),
    path('expiry-clients-list/', ClientsDataView.as_view(), name='expiry-clients'),
    path('sub-segments-list/', SubSegmentsView.as_view(), name='sub_segments'),
    path('update-trade-status/', UpdateTradeSettingStatusView.as_view(), name='update_client_setting'),
    path('client-trade-settings/update/', UpdateClientTradeSettingAPIView.as_view(), name='update-trade-setting'),
    path('get-client-trade-setting/', GetTradeSettingAPIView.as_view(), name='get-trade-settings'),   
    path('clients/trading/status/count/', ClientTradingStatusCountView.as_view(), name='client-trading-status-count'),
    path('clients/onboarding/stats/', ClientOnboardingStatsView.as_view(), name='client-onboarding-stats'),

 
    path('get-client-segments-list/', UpdateTradeSettingStatusView.as_view(), name='get-trade-settings'),
    # path('get-count-client/',SubAdminAllClientView.as_view(),name='active-inactive-client')
    path('active-inactive-clients/<int:id>/', clientActiveInactiveView.as_view(), name='user-detail'),
    path('clients-by-group-service/<int:group_service_id>/', ClientsByGroupServiceView.as_view(), name='clients-by-group-service'),
    path('active-client-list/', ActiveClientsView.as_view(), name='get-active-client-list'),
    path('inactive-client-list/',InactiveClientsView.as_view(),name='get-inactive-client-list'),
    path('all-subadmins-list/', UserManagementView.as_view(), name='user-management'),
    path("order-webhook/",PlaceOrderWebhookView.as_view(),name='create-order-webhook'),
    path("get-client-trade/",GetclientdataView.as_view(),name='get-client-trade'),
    path('strategies/<int:strategy_id>/clients/', StrategyClientListView.as_view(), name='strategy-client-list'),
    path("get-client-details/",ClientDashboardIView.as_view(),name='get-client-details'),
    path("get-client-Trade-status/",ClientsTradeStatusView.as_view(),name='client-trading-status'),
    path("client/<int:client_id>/update-trade-status/",ClientsTradeStatusView.as_view(),name='clienttrade-status-by-id'),
    path("get-client-broker-details/", ClientBrokerDetailsView.as_view(), name='get-client-broker'),
    path("update-client-broker/", ClientBrokerDetailsView.as_view(), name='update-client-broker'),
    path("enable-disable-broker/", EnableDisableBrokerView.as_view(), name='update-status-broker'),
    path("get-client-api-status/", EnableDisableBrokerView.as_view(), name='get-status-broker'),
    path('get-sub-segments-by-segment/', SubSegmentsListView.as_view(), name='sub-segments-list'),
    # path('get-expiry-date-list/', SymbolExpirDateListView.as_view(), name='expiry-date-list'),
    path('get-expiry-date-list/', SymbolExpiryDateListView.as_view(), name='download-nfo-csv'),
    path('update-client-status/<int:pk>/', ClientCreateView.as_view(), name='update-client-status'),
    path('get-trade-history/', TradeorderhistoryListView.as_view(), name='get-trade-history'),  
    path('get-client-trade-history/', ClientTradeListView.as_view(), name='get-client-trade-history'), 
    path('clients-filter/', ClientFilterView.as_view(), name='client-list'),   
    path('client-dashboard-redirect/',ClientDashBoardView.as_view(),name='client-dashboard-'),   
    path('trade-order-response/<int:trade_id>/', TradeOrderResponseDataView.as_view(), name='trade-order-response'),

    path("broker_auth_login/",BrokerLoginRedirectView.as_view(), name="login_broker"),#AUTH2.0
   
    path("auth-callback/", BrokerCallbackView.as_view(), name="broker_callback"),
    
    path('get-company-profile/', CompanyProfileDetailView.as_view(), name='get-company_profile_detail'),
    path('update-company-profile/', CompanyProfileUpdateView.as_view(), name='put-company_profile_detail'),
    path('get-company-smtp/', CompanySmtpDetailView.as_view(), name='get-company-smtp-detail'),  
    path('update-company-smtp/', CompanySmtpUpdateView.as_view(), name='put-company-smtp-detail'), 
    
    path("create-order/", CreateOrderView.as_view(), name="create-order"),
    path("payment-callback/", PaymentCallbackView.as_view(), name="payment-callback"),
    path("verify-payment/", VerifyPaymentAPIView.as_view(), name="payment-callback"),
    # path('callback/', views.oauth_callback, name='oauth_callback'),
    # path('login-5paisa/', views.login_redirect, name='login_redirect'),
    path("login-5paisa/",initiate_oauth_login, name="initiate_oauth"),
    path("callback-5paisa/", oauth_callback, name="oauth_callback"),

    path('login-zerodha/', views.login_zerodha_redirect, name='login-zerodha'),
    path('callback-zerodha/', views.zerodha_callback, name='zerodha-callback'),
    path('login-angelone/', views.login_angelone_redirect, name='login-angelone'),
    path('callback-angelone/', views.angelone_callback, name='angelone-callback'),
    path("callback/aliceblue/", views.aliceblue_callback, name="aliceblue_callback"),
    path("login-aliceblue/", views.login_aliceblue, name="login_aliceblue"),
    path("place-zerodha-order/", place_zerodha_order, name="zerodha-order"),
    path('login-upstox/',get_upstox_login_url,name="login_upstox_redirect"),
    path('callback-upstox/',callback_upstox,name="login_upstox_redirect"),
    path("broker-login/", LoginDematAPIView.as_view(), name="login_broker"),
    
    path('trade-history-filter/', TradeOrderHistoryFilterView.as_view(), name='trade_history_filter'),
    path("get-websocket-token/", WebsocketTokenView.as_view(), name="websocket-token"),
    path("update-websocket-token/", UpdateWebSocketToken.as_view(), name="websocket-token"),
    path('get-strategies-tradehistory/', StrategyListView.as_view(), name='get-strategies-tradehistory'), # for get the tradehistory strategy

    path('get-client-strategies-tradesetting/', ClientStrategyListView.as_view(), name='get-client-strategies-tradesetting'),
    path('get-broker-token-expiry/',CheckTokenValidityView.as_view(),name="client-broker-istokenexpiry"),
    path('get-client-broker-status-by-id/<int:pk>/', AdminGetClientBrokerStatusView.as_view(), name='client-status'),
    path("get-client-broker-details-by-id/<int:pk>/", AdminClientBrokerDetailsView.as_view(), name='get-client-broker'),
    path('broker-log-activity/<int:id>/', BrokerLogActivityView.as_view(), name='broker-log-activity'),
    path('user-broker-log/<int:user_id>/', UserBrokerLogActivityView.as_view(), name='user-broker-log'),
    
    path('client-broker-details-setting-aleart/', GetClientBrokerDetailsSettingView.as_view(), name='client-broker-details'),
    path('client-complete-trade-history/',TradeCompleteListView.as_view(), name='client-completed-trade-details'),
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

